- name: set set-hostname
  ansible.builtin.shell: set-hostname {{env}}-{{component}}


- name: disable the nodejs default
  ansible.builtin.shell: dnf module disable nodejs -y

- name: enable the nodejs 
  ansible.builtin.shell: dnf module enable nodejs:18 -y

- name: install the nodejs
  ansible.builtin.dnf:
    name: nodejs
    state: present

- name: user add expense
  ansible.builtin.user:
    name: expense

- name: import the common role
  ansible.builtin.import_role:
    name: common
    tasks_from: app-req
  vars:
     app_dir: /app
     component: backend  

- name: install the nodejs dependencies
  ansible.builtin.shell: npm install 
  args:
    chdir: /app

- name: install the client mysql server
  ansible.builtin.dnf:
    name: mysql
    state: present

- name: load the schema
  ansible.builtin.shell: mysql -h <MYSQL-SERVER-IPADDRESS> -uroot -p{{MYSQL_ROOT_PASSWORD}} < /app/schema/backend.sql 

- name: restart the backend services
  ansible.builtin.systemd:
    name: backend
    state: restarted
    enabled: yes
