- name: sethostname 
  ansible.builtin.shell: set-hostname {{env}}-{{component}}

- name: install the nginx
  ansible.builtin.dnf:
    name: nginx
    state: present

- name: copy the expense.conf file
  ansible.builtin.template:
    src: expense.conf
    dest: /etc/nginx/default.d/expense.conf
    
- name: import the common role
  ansible.builtin.import_role:
    name: common
    tasks_from: app-req
  vars:
    app_dir: /usr/share/nginx/html
    component: frontend

- name: import the common role
  ansible.builtin.import_role:
    name: elk
    tasks_from: filebeat 
- name: import the common role
  ansible.builtin.import_role:
    name: prometheus
    tasks_from: node-exporter     

- name: enable and start the services
  ansible.builtin.systemd:
     name: nginx
     state: restarted
     enabled: yes


