 - name: copy the elastic repo
   ansible.builtin.template:
      src: elastic.repo
      dest: /etc/yum.repos.d/elastic.repo
 - name: install the filebeat
   ansible.builtin.dnf:
      name: filebeat
      state: installed