- name: disableq the mysql
  ansible.builtin.shell: dnf module disable mysql -y 

- name: copy the mysql repo file
  ansible.builtin.template: 
     src: mysql.repo
     dest: /etc/yum.repos.d/mysql.repo


- name: install the mysql mysql-community-server
  ansible.builtin.dnf:
    name: mysql-community-server
    state: present

- name: change the default root password of mysql
  ansible.builtin.shell: mysql_secure_installation --set-root-pass "$MYSQL_ROOT_PASSWORD"

- name: restart the services
  ansible.builtin.systemd:
    name: mysqld
    state: restartede
    enabled: yes

    