groups:
  - name: example-rules
    rules:
      - alert: HighMemoryUsage
        expr: node_memory_Active_bytes > 1000000000
        for: 5m
        annotations:
          description: "Memory usage is too high on the node."
        labels:
          severity: critical