groups:
  - name: node_exporter
    labels:
      team: myteam
    rules:
      - alert: InstanceDown
        expr: up < 1
        for: 1m
        labels:
          severity: page
        annotations:
          summary: instance down
          