groups:
- name: node_exporter
  labels:
    team: myteam
  rules:
  - alert: instance down alert
    expr: up < 0
    for: 1m
    labels:
      severity: page
    annotations:
      summary: Instance down alert